### ISSUE TITLE
team mjolnir: application checklist

### ISSUE THREAD

**Issue by pongstr** [pongstr/boxen#46]
### Approved apps

- [x] atom: via `brewcask` provider
- [x] Chrome: via `brewcask` provider
- [x] Chrome Canary: via `brewcask` provider
- [x] Cyberduck: via [`puppet-cyberduck`](https://github.com/pongstr/puppet-cyberduck) provider
- [x] Dashlane: via `puppet-dashlane` provider
- [x] Firefox: via `puppet-firefox` provider
- [x] MongoDB: via `puppet-mongodb` provider
- [x] Nginx: via `puppet-nginx` provider
- [x] Python: via `puppet-python` provider
- [x] RoboMongo: via `brewcask` provider
- [x] Sublime Text: via `puppet-sublime_text` provider
- [x] Virtualbox: via `puppet-virtualbox` provider
- [x] VLC: via `puppet-vlc` provider
- [x] Webstorm: via [`puppet-webstorm`](https://github.com/pongstr/puppet-webstorm) provider
- [x] Zshell: via `puppet-zsh` provider

----

### Projects

Projects are ready, just add water. Actually just add your Bitbucket `.ssh` key. We haven't figured out how to do this **the boxen way**, so temporarily you may curl this [`.gituser` dotfile](https://github.com/pongstr/dotfiles/blob/master/init/.gituser) to make ssh-key adding a breeze.

```bash
# Download the file
$ curl -L -O https://raw.githubusercontent.com/pongstr/dotfiles/master/init/.gituser 

# Make it executable and run it, follow instructions and you're golden
$ chmod +x .gituser && ./.gituser
```
