### ISSUE TITLE
team osiris: application checklist

### ISSUE THREAD

**Issue by pongstr** [pongstr/boxen#49]
- [x] atom
- [x] boot2docker
- [x] chrome
- [x] dashlane
- [x] firefox
- [x] github_for_mac
- [x] hipchat
- [x] iterm2
- [x] mysql
- [x] mysqlworkbench (via brewcask)
- [x] python
- [x] sourcetree
- [x] sql developer (via _ )
- [x] sublime text
- [x] vagrant
- [x] vim (via brew)
- [x] virtualbox
- [x] vlc
- [x] zsh

the rest are all from puppets

**Comment by femee24** [comment]
-{} chrome
-{} firefox
-{} hipchat
-{} dashlane
-{} sublime text!
-{} vlc
-{} virtualbox
-{} iterm2
-{} mysql
-{} github_for_mac
-{} boot2docker
-{} sourcetree
-{} python
-{} zsh (oh my zsh)
-{} vagrant
-{} vim
-{} mysqlworkbench
-{} atom
