### ISSUE TITLE
team vishnu: application checklist

### ISSUE THREAD

**Issue by pongstr** [pongstr/boxen#50]
//cc @devcsrj @femee24 : please update when necessary

- [x] atom: installed via `brewcask` provider
- [x] boot2docker: installed via [`puppet-boot2docker`](https://github.com/femee24/boot2docker)
- [x] chrome: installed via `puppet-provider` provider
- [x] dashlane: installed via `puppet-dashlane` provider
- [x] dbvisualier: installed via `brewcask` provider
- [x] diffgmerge: installed via `brewcask` provider
- [x] firefox: installed via `puppet-firefox` provider
- [x] github UI: installed via `brewcask` provider `puppet-github_for_mac` 
  is deprecated as per prohject repo
- [x] groovy: installed via `homebrew` provider
- [x] hipchat: installed via `puppet-hipchat` provider
- [x] jenv: installed via `brewcask` provider [http://www.jenv.be](http://www.jenv.be)
- [ ] java 8: installed via `brewcask` provider
- [x] java 7: installed via `brewcask` provider
- [ ] java 6: installed via `brewcask` provider
- [ ] jd-gui: ???
- [x] mysql: installed via `puppet-mysql` provider
- [x] mysqlworkbench: installed via `` provider
- [x] nginx: installed via `` provider
- [x] pgadmin: installed via `brewcask` provider
- [x] postgresql: installed via `puppet-postgresql` provider
- [x] python: installed via `puppet-python` provider
- [x] redis: installed via `puppet-redis` provider
- [x] soapui: installed via `package:pkgdmg` provider
- [x] solr: installed via `puppet-solr` provider
- [ ] squirrel-sql: installed via `package::exec` provider (java must be installed first)
- [x] sourcetree: installed via `puppet-sourcetree` provider
- [x] sqlpowerarchitect: installed via `package:compressed_app` provider
- [x] spring tool suite: installed via `` provider
- [x] sublime text: installed via `` provider
- [x] talend: installed via `package::compressed_app` provider
- [x] textwrangler: installed via `puppet-textwrangler` provider
- [x] tomcat: installed via `brewcask` provider (java must be installed first)
- [x] vagrant: installed via `puppet-vagrant` provider
- [x] vim: uses osx system default, not upgradable but may be override 
  via `brewcask` prpvider
- [x] virtualbox: installed via `` provider
- [x] vlc: installed via `puppet-vlc` provider
- [x] wget: installed via `puppet-wget` provider
- [x] zsh: installed via `puppet-zsh` provider

**Comment by devcsrj** [comment]
Skipping installations of:
- `java 8`, `java 6` - configured only `java7` as minimum required.
- `jd-gui` - boxen doesn't support yet `.tar`
- `squirrel-sql` - boxen doesn't support yet native java installers
